# Generated by Django 4.2.1 on 2023-05-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="menuHoursModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.BigIntegerField()),
                ("start_time_local", models.DateTimeField()),
                ("end_time_local", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="storeStatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.BigIntegerField()),
                ("status", models.CharField(max_length=50)),
                ("timestamp_uct", models.DateTimeField()),
            ],
        ),
    ]
