# Generated by Django 4.2.1 on 2023-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapiapp", "0003_alter_menuhoursmodel_end_time_local"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuhoursmodel",
            name="day_num",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
