# Generated by Django 4.2.1 on 2023-05-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapiapp", "0005_alter_menuhoursmodel_end_time_local_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="timezoneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.BigIntegerField()),
                ("timezone_str", models.CharField(max_length=100)),
            ],
        ),
    ]
